// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Builds the datasource URL for Prisma CLI (migrate/generate/seed).
 * Prefer DATABASE_URL when set; otherwise compose from MYSQL_* vars.
 * A placeholder URL is used only so `prisma generate` works in Docker builds
 * without baking real credentials into the image.
 */
function buildDatabaseUrl() {
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }

  const { MYSQL_USER, MYSQL_PASSWORD, MYSQL_HOST, MYSQL_PORT, MYSQL_DATABASE } = process.env;

  if (MYSQL_USER && MYSQL_PASSWORD && MYSQL_HOST && MYSQL_PORT && MYSQL_DATABASE) {
    return `mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}`;
  }

  return "mysql://build:build@127.0.0.1:3306/teacher_lesson_blog";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
